### ISSUE TITLE
v2.0.0: undefined local variable or method `dir_path' for #<Licensed::Dependency:0x0zzz>

### ISSUE THREAD

**Issue by parkr** [github/licensed#141]
I just upgraded to v2.0.0 (🎉) but running `licensed cache` failed:

```text
~/my/project#master$ ./script/licensed cache
If you encounter rate-limiting errors, please set the GITHUB_TOKEN environment variable and try again.
Caching dependency records for GitHub Pages
  bundler
bundler: failed to load command: licensed (/Users/parkr/my/project/vendor/gems/ruby/2.5.0/bin/licensed)
NameError: undefined local variable or method `dir_path' for #<Licensed::Dependency:0x00007f8a56919d20>
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/dependency.rb:92:in `notice_files'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/dependency.rb:83:in `notice_contents'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/dependency.rb:61:in `record'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/commands/cache.rb:39:in `evaluate_dependency'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/commands/command.rb:91:in `block in run_dependency'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/reporters/cache_reporter.rb:61:in `block in report_dependency'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/reporters/reporter.rb:111:in `report_dependency'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/reporters/cache_reporter.rb:60:in `report_dependency'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/commands/command.rb:84:in `run_dependency'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/commands/command.rb:63:in `block (2 levels) in run_source'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/commands/command.rb:63:in `map'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/commands/command.rb:63:in `block in run_source'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/reporters/cache_reporter.rb:28:in `block in report_source'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/reporters/reporter.rb:89:in `report_source'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/reporters/cache_reporter.rb:26:in `report_source'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/commands/command.rb:61:in `run_source'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/commands/cache.rb:21:in `run_source 31 gem "jekyll-geo-pattern", "~> 0.4.1"
'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/commands/command.rb:44:in `block (3 levels) in run_app'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/commands/command.rb:44:in `map'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/commands/command.rb:44:in `block (2 levels) in run_app'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/commands/command.rb:42:in `chdir'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/commands/command.rb:42:in `block in run_app'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/reporters/cache_reporter.rb:14:in `block in report_app'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/reporters/reporter.rb:66:in `report_app'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/reporters/cache_reporter.rb:12:in `report_app'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/commands/command.rb:41:in `run_app'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/commands/command.rb:23:in `block (2 levels) in run'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/commands/command.rb:23:in `map'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/commands/command.rb:23:in `block in run'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/reporters/reporter.rb:44:in `report_run'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/commands/command.rb:22:in `run'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/cli.rb:74:in `run'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/lib/licensed/cli.rb:14:in `cache'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/gems/licensed-2.0.0/exe/licensed:5:in `<top (required)>'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/bin/licensed:23:in `load'
  /Users/parkr/my/project/vendor/gems/ruby/2.5.0/bin/licensed:23:in `<top (required)>'
```

**Comment by jonabc** [comment]
Thanks for the report! I would have assumed something like this would be hit by the manual or automated testing.  Will take a look and see whats going on

**Comment by jonabc** [comment]
@parkr looks like this is due to using an older version of `licensee` that doesn't include the `Licensee::Projects::FSProject#dir_path`🤦‍♂️ .  Since this occurs on a recent major release I'm going to resolve this by updating the `licensee` version requirement in the gemspec and cut a new release.
