### ISSUE TITLE
Crash while listing deps in github/semantic

### ISSUE THREAD

**Issue by patrickt** [github/licensed#228]
To reproduce:
* check out https://github.com/github/semantic
* install `ghcup`
* `ghcup set 8.8`
* `cabal configure --disable-optimization`
* `cabal build --only-dependencies`
* `licensed list`

The error I got follows:
```
Traceback (most recent call last):
	34: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/bin/licensed:23:in `<main>'
	33: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/bin/licensed:23:in `load'
	32: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/exe/licensed:5:in `<top (required)>'
	31: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	30: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	29: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	28: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	27: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/cli.rb:28:in `list'
	26: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/cli.rb:83:in `run'
	25: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/commands/command.rb:22:in `run'
	24: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/reporters/reporter.rb:61:in `report_run'
	23: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/commands/command.rb:27:in `block in run'
	22: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/commands/command.rb:27:in `map'
	21: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/commands/command.rb:27:in `block (2 levels) in run'
	20: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/commands/command.rb:56:in `run_app'
	19: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/reporters/list_reporter.rb:13:in `report_app'
	18: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/reporters/reporter.rb:83:in `report_app'
	17: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/reporters/list_reporter.rb:15:in `block in report_app'
	16: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/commands/command.rb:57:in `block in run_app'
	15: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/commands/command.rb:57:in `chdir'
	14: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/commands/command.rb:64:in `block (2 levels) in run_app'
	13: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/commands/command.rb:64:in `map'
	12: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/commands/command.rb:64:in `block (3 levels) in run_app'
	11: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/commands/command.rb:81:in `run_source'
	10: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/reporters/list_reporter.rb:27:in `report_source'
	 9: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/reporters/reporter.rb:106:in `report_source'
	 8: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/reporters/list_reporter.rb:29:in `block in report_source'
	 7: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/commands/command.rb:86:in `block in run_source'
	 6: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/sources/source.rb:48:in `dependencies'
	 5: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/sources/source.rb:65:in `cached_dependencies'
	 4: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/sources/cabal.rb:15:in `enumerate_dependencies'
	 3: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/sources/cabal.rb:15:in `map'
	 2: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/sources/cabal.rb:16:in `block in enumerate_dependencies'
	 1: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/sources/cabal.rb:55:in `package_docs_dirs'
/__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.7.0/lib/licensed/sources/cabal.rb:55:in `join': no implicit conversion of nil into String (TypeError)
```

I used this configuration:
```yaml
allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense

cabal:
  ghc_package_db: "~/.cabal/store/ghc-8.8.1/package.db"
  cabal_file_targets:
    - common
    - library
    - executable
```

**Comment by jonabc** [comment]
👋 @patrickt I took a look and theres a few things going on, but luckily none of them are fully blocking based on ☝️ 

1. you need to include `global` as a packagedb arg in your licensed configuration file to pick up packages like `base`, which was a failing package that I noticed when debugging.
2. you also need to include the local `dist-newstyle` packagedb location to pick up some of the locally built packages

Once those two things are done I wasn't seeing a crash, but following the above instructions I was still seeing an error that the `semantic` package couldn't be found.  That makes sense since the instructed command `cabal build --only-dependencies` wouldn't build semantic itself.  That error can be bypassed by either building semantic, or ignoring the semantic package in the licensed configuration (generally this tool is for documenting 3rd party metadata and semantic here isn't 3rd party).

I ended up with the following configuration
```
allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense

ignored:
  cabal:
    - semantic*

cabal:
  ghc_package_db:
    - "~/.cabal/store/ghc-<ghc_version>/package.db"
    - dist-newstyle/packagedb/ghc-<ghc_version>
    - global
  cabal_file_targets:
    - common
    - library
    - executable
```

I'm going to leave this open to track work that should prevent the crash from happening in the future.

**Comment by jonabc** [comment]
Notes for a fix: the cabal source already handles missing packages if they are [top-level references from the cabal file](https://github.com/github/licensed/blob/2cf0b7fb6d0251df34da58c94fe70331dd755680/lib/licensed/sources/cabal.rb#L39-L40).  This same protection should be extended to packages that are found recursively via [package_info](https://github.com/github/licensed/blob/2cf0b7fb6d0251df34da58c94fe70331dd755680/lib/licensed/sources/cabal.rb#L110-L117)
