### ISSUE TITLE
Source path glob patterns do not work for a single match

### ISSUE THREAD

**Issue by AlekSi** [github/licensed#309]
Documentation recommends to use `source_path: cmd/*` for idiomatic Go projects. However, this explodes if there is only one match (and possibly zero; did not test this case).

```
./licensed cache
Caching dependency records for *
Traceback (most recent call last):
	20: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/bin/licensed:23:in `<main>'
	19: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/bin/licensed:23:in `load'
	18: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.12.2/exe/licensed:5:in `<top (required)>'
	17: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	16: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	15: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	14: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	13: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.12.2/lib/licensed/cli.rb:16:in `cache'
	12: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.12.2/lib/licensed/cli.rb:99:in `run'
	11: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.12.2/lib/licensed/commands/cache.rb:23:in `run'
	10: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.12.2/lib/licensed/commands/command.rb:22:in `run'
	 9: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.12.2/lib/licensed/reporters/reporter.rb:64:in `report_run'
	 8: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.12.2/lib/licensed/commands/command.rb:29:in `block in run'
	 7: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.12.2/lib/licensed/commands/command.rb:29:in `map'
	 6: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.12.2/lib/licensed/commands/command.rb:29:in `block (2 levels) in run'
	 5: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.12.2/lib/licensed/commands/command.rb:58:in `run_app'
	 4: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.12.2/lib/licensed/reporters/cache_reporter.rb:12:in `report_app'
	 3: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.12.2/lib/licensed/reporters/reporter.rb:86:in `report_app'
	 2: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.12.2/lib/licensed/reporters/cache_reporter.rb:14:in `block in report_app'
	 1: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.12.2/lib/licensed/commands/command.rb:59:in `block in run_app'
/__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.12.2/lib/licensed/commands/command.rb:59:in `chdir': No such file or directory @ dir_chdir - /XXX/licensed-test/cmd/* (Errno::ENOENT)
```

See:
* https://github.com/percona-platform/licensed-test/tree/one-cmd
* https://github.com/percona-platform/licensed-test/pull/1
* https://github.com/percona-platform/licensed-test/pull/1/checks?check_run_id=1158970311

**Comment by jonabc** [comment]
🚀 thanks for the bug report.  The root cause is a (potentially wrong) [check](https://github.com/github/licensed/blob/573e0b4dc5826b0e4ef1f64f7a40ccdd69bebf6b/lib/licensed/configuration.rb#L163-L164) on whether expanding a source path did result in an expansion.  I'll take a look at handling this better 👍
