### ISSUE TITLE
Incompatibility with Bundler 2.3.19

### ISSUE THREAD

**Issue by gschlager** [github/licensed#521]
https://github.com/rubygems/rubygems/commit/9f5832e1fe6ce08486d34209cc260a619d077e4b broke the gem.

```
/usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/sources/bundler/missing_specification.rb:43:in `__materialize__': wrong number of arguments (given 1, expected 0) (ArgumentError)
  * 0 bundler dependencies
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.19/lib/bundler/lazy_specification.rb:79:in `materialize_for_installation'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.19/lib/bundler/spec_set.rb:74:in `block in materialize'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.19/lib/bundler/spec_set.rb:71:in `map!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.19/lib/bundler/spec_set.rb:71:in `materialize'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/sources/bundler/definition.rb:17:in `specs'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/sources/bundler.rb:61:in `block in enumerate_dependencies'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/sources/bundler.rb:117:in `block in with_application_environment'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.19/lib/bundler/ui/shell.rb:136:in `with_level'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.19/lib/bundler/ui/shell.rb:[8](https://github.com/discourse/discourse/runs/7552274881?check_suite_focus=true#step:10:9)8:in `silence'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/sources/bundler.rb:105:in `with_application_environment'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/sources/bundler.rb:60:in `enumerate_dependencies'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/sources/source.rb:8[9](https://github.com/discourse/discourse/runs/7552274881?check_suite_focus=true#step:10:10):in `cached_dependencies'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/sources/source.rb:72:in `dependencies'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/commands/command.rb:136:in `run_source'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/commands/cache.rb:54:in `run_source'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/commands/command.rb:[10](https://github.com/discourse/discourse/runs/7552274881?check_suite_focus=true#step:10:11)1:in `block (2 levels) in run_app'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/commands/command.rb:98:in `map'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/commands/command.rb:98:in `block in run_app'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/commands/command.rb:95:in `chdir'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/commands/command.rb:95:in `run_app'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/commands/cache.rb:40:in `block in run_app'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/commands/cache.rb:166:in `with_licensee_configuration'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/commands/cache.rb:39:in `run_app'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/commands/command.rb:67:in `block in run_command'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/commands/command.rb:64:in `map'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/commands/command.rb:64:in `run_command'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/commands/cache.rb:24:in `run_command'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/commands/command.rb:23:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/cli.rb:[11](https://github.com/discourse/discourse/runs/7552274881?check_suite_focus=true#step:10:12)0:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/lib/licensed/cli.rb:18:in `cache'
	from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:[12](https://github.com/discourse/discourse/runs/7552274881?check_suite_focus=true#step:10:13)7:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/gems/2.7.0/gems/licensed-3.7.2/exe/licensed:5:in `<top (required)>'
	from /usr/local/bin/licensed:[25](https://github.com/discourse/discourse/runs/7552274881?check_suite_focus=true#step:10:26):in `load'
	from /usr/local/bin/licensed:25:in `<main>'
```

**Comment by gschlager** [comment]
Fixed
