### ISSUE TITLE
Failing to parse json from pnpm/npm

### ISSUE THREAD

**Issue by elliotcourant** [github/licensed#759]
I've been using licensed for a long time now and have never run into an issue like this; so I'm not sure what the problem could be.

The failure I get looks like this when running the report: 

```
144.7     Caching gopkg.in/ezzarghili/recaptcha-go.v4 (v4.3.0)
144.7     Caching gopkg.in/ini.v1 (v1.67.0)
144.7     Caching gopkg.in/yaml.v3 (v3.0.1)
144.8     Caching mellium.im/sasl (v0.3.1)
144.8   * 756 go dependencies
144.8 Caching dependency records for monetr-UI
144.9   npm
148.4     Caching @adobe/css-tools (4.4.0)
148.4     Using @alloc/quick-lru (5.2.0)
148.4   * 2 npm dependencies
148.4 /monetr/build/ruby/gems/json-2.8.1/lib/json/common.rb:204:in `encode': "\\xE2" on US-ASCII (Encoding::InvalidByteSequenceError)
148.4 	from /monetr/build/ruby/gems/json-2.8.1/lib/json/common.rb:204:in `parse'
148.4 	from /monetr/build/ruby/gems/json-2.8.1/lib/json/common.rb:204:in `parse'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/lib/licensed/sources/npm.rb:18:in `license_metadata'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/lib/licensed/dependency.rb:62:in `record'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/lib/licensed/commands/cache.rb:89:in `evaluate_dependency'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/lib/licensed/commands/command.rb:176:in `run_dependency'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/lib/licensed/commands/command.rb:140:in `block in run_source'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/lib/licensed/commands/command.rb:137:in `map'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/lib/licensed/commands/command.rb:137:in `run_source'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/lib/licensed/commands/cache.rb:55:in `run_source'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/lib/licensed/commands/command.rb:101:in `block (2 levels) in run_app'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/lib/licensed/commands/command.rb:98:in `map'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/lib/licensed/commands/command.rb:98:in `block in run_app'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/lib/licensed/commands/command.rb:95:in `chdir'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/lib/licensed/commands/command.rb:95:in `run_app'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/lib/licensed/commands/cache.rb:41:in `block in run_app'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/lib/licensed/commands/cache.rb:175:in `with_licensee_configuration'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/lib/licensed/commands/cache.rb:40:in `run_app'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/lib/licensed/commands/command.rb:67:in `block in run_command'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/lib/licensed/commands/command.rb:64:in `map'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/lib/licensed/commands/command.rb:64:in `run_command'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/lib/licensed/commands/cache.rb:24:in `run_command'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/lib/licensed/commands/command.rb:23:in `run'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/lib/licensed/cli.rb:115:in `run'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/lib/licensed/cli.rb:18:in `cache'
148.4 	from /monetr/build/ruby/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
148.4 	from /monetr/build/ruby/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
148.4 	from /monetr/build/ruby/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
148.4 	from /monetr/build/ruby/gems/thor-1.3.2/lib/thor/base.rb:584:in `start'
148.4 	from /monetr/build/ruby/gems/licensed-4.4.0/exe/licensed:5:in `<top (required)>'
148.4 	from /monetr/build/ruby/bin/licensed:25:in `load'
148.4 	from /monetr/build/ruby/bin/licensed:25:in `<main>'
```

When running `licensed cache` in my project's base directory. [Available here if you want to try to reproduce](https://github.com/monetr/monetr)

I also get the same failure on 5.0.0; both using pnpm 9.12.3 (which it has been using since it came out). 

The output of `pnpm licenses list --json --long` also seems to be perfectly valid json.

---

### Steps to reproduce

1. Clone repo
   ```
   git clone https://github.com/monetr/monetr.git
   cd monetr
   ```
2. Install dependencies
   ```
   go mod download && pnpm install
   ```
3. Try to cache via licensed
   ```
   licensed cache
   ```

**Comment by elliotcourant** [comment]
Another note is that the step in our build where we generate the third party notice files from licensed succeeded for the same commit in the PR: https://github.com/monetr/monetr/actions/runs/11687819458/job/32546795546

But failed when merged to main: https://github.com/monetr/monetr/actions/runs/11725320747/job/32669223132

Inside the container, the same versions of pnpm, node, ruby and licensed. 
- pnpm: 9.12.3
- node: 18.19.0
- ruby: 3.1.2
- licensed: 4.4.0

**Comment by elliotcourant** [comment]
Digging in more; its not even using pnpm so that isn't the problem. The stack trace has it on this line? https://github.com/github/licensed/blob/20ccab13f3e8738cf12543ef78da3469bf63c249/lib/licensed/sources/npm.rb#L18 which means its failing to parse my package.json file? But that doesn't make sense either?

**Comment by elliotcourant** [comment]
I was able to fix this so I'll close the issue; no idea why this suddenly started happening (maybe debian changed their container upstream?)

But I found this: https://superuser.com/questions/975101/issues-running-ruby-script-as-cron-job which made me think the locale changed, so adding `locales-all` to the build step and then setting LANG=en_US.UTF-8 fixed it.

https://github.com/monetr/monetr/commit/0eb0f215915578efc084e816aba62a2801db72ec
